### ISSUE TITLE
Create a grid view for tiles in menu page

### ISSUE THREAD

**Issue by Serjeel-Ranjan-911** [Serjeel-Ranjan-911/Titan-Beats#6]
Currently tiles on menu page doesn't look good on all the devices. Make it more uniform to look good on all the devices. 
check the code in scss/__menu.scss. Preferably implement it using CSS grids.

**Comment by dp46504** [comment]
I can do it on flexbox and css

**Comment by Serjeel-Ranjan-911** [comment]
go ahead. I preferred css grid since it's good for designing grids. However if you can do it with flexbox then great. With pull request attach few screenshots on various devices. Please exchange follow ;).

**Comment by Serjeel-Ranjan-911** [comment]
Ok I just saw you already sent pull request

**Comment by Serjeel-Ranjan-911** [comment]
Here there is a lot of empty space on left and right side can we utilize that space too? I mean 3X2 grid. 
![image](https://user-images.githubusercontent.com/74287984/114870274-95d1f980-9e15-11eb-9ee7-cbcc140033ed.png)
plus on phones again single tile is a bit too much a 2X6 grid should be better here
![image](https://user-images.githubusercontent.com/74287984/114870397-c154e400-9e15-11eb-97fd-e489ab6e9858.png)

extra: scale down the title on small devices

**Comment by dp46504** [comment]
Ok i will work on this
